const DISHES = [
  {
    id: "dhokla",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Dhokla", gu: "ઢોકળા" },
    mealTime: ["morning", "snack"],
    excludeDays: [],
    tags: ["steamed", "fermented", "light", "satvic", "chana", "everyday"],
    ingredients: "ચોખા, ચણાની દાળ, દહીં, આદુ, લીલા મરચાં",
    note: "Steamed & light — easy on digestion",
  },
  {
    id: "khaman",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Khaman", gu: "ખમણ" },
    mealTime: ["morning", "snack"],
    excludeDays: [],
    tags: ["steamed", "fermented", "light", "satvic", "chana", "everyday"],
    ingredients: "ચણાનો લોટ, લીંબુના ફૂલ, ખાંડ, મીઠું, તેલ",
    note: "Soft besan khaman with green chutney",
  },
  {
    id: "thepla",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Thepla", gu: "થેપલા" },
    mealTime: ["morning", "lunch", "snack"],
    excludeDays: [],
    tags: ["baked", "light", "satvic", "grain", "leafy", "everyday"],
    ingredients: "ઘઉંનો લોટ, મેથીની ભાજી, દહીં, મસાલા, તેલ",
    note: "Methi thepla with dahi or achaar",
  },
  {
    id: "handvo",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Handvo", gu: "હાંડવો" },
    mealTime: ["morning", "snack"],
    excludeDays: [],
    tags: ["baked", "fermented", "heavy", "satvic", "grain", "everyday"],
    ingredients: "ચોખા, ચણાની દાળ, તુવેરની દાળ, દૂધી, દહીં, તેલ",
    note: "Baked savory cake — filling and wholesome",
  },
  {
    id: "poha",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Poha", gu: "પૌંઆ" },
    mealTime: ["morning", "snack"],
    excludeDays: [],
    tags: ["light", "satvic", "grain", "everyday"],
    ingredients: "પૌંઆ, બટાટા, ડુંગળી, મગફળી, લીંબુ, મસાલા",
    note: "Quick and light — ideal morning meal",
  },
  {
    id: "methi_gota",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Methi Gota", gu: "મેથી ના ગોટા" },
    mealTime: ["morning", "snack"],
    excludeDays: [],
    months: [7, 8, 9, 10, 11, 12, 1, 2, 3],
    tags: [
      "fried",
      "heavy",
      "rajasic",
      "warming",
      "chana",
      "leafy",
      "everyday",
    ],
    ingredients: "ચણાનો લોટ, મેથીની ભાજી, મરી, આખા ધાણા, તેલ",
    note: "Crispy fenugreek fritters — monsoon and winter both",
  },
  {
    id: "fafda_jalebi",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Fafda Jalebi", gu: "ફાફડા જલેબી" },
    mealTime: ["morning"],
    excludeDays: [1, 2, 3, 4, 5],
    tags: ["fried", "heavy", "rajasic", "chana", "grain", "festive"],
    ingredients: "ચણાનો લોટ, અજમો, તેલ, મેંદો, ખાંડ, કેસર",
    note: "The sacred Sunday morning ritual",
  },
  {
    id: "muthiya",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Muthiya", gu: "મૂઠિયા" },
    mealTime: ["morning", "snack"],
    excludeDays: [],
    tags: ["steamed", "light", "satvic", "grain", "leafy", "everyday"],
    ingredients: "ઘઉંનો કકરો લોટ, ચણાનો લોટ, મેથીની ભાજી, દૂધી, તેલ",
    note: "Steamed methi dumplings — wholesome and satvic",
  },
  {
    id: "upma",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Upma", gu: "ઉપ્મા" },
    mealTime: ["morning", "snack"],
    excludeDays: [],
    tags: ["light", "satvic", "grain", "everyday"],
    ingredients: "રવો, ડુંગળી, ગાજર, વટાણા, રાઈ, લીમડો",
    note: "Semolina upma — light and quick",
  },
  {
    id: "rava_dhokla",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Rava Dhokla", gu: "રવા ઢોકળા" },
    mealTime: ["morning", "snack"],
    excludeDays: [],
    tags: ["steamed", "light", "satvic", "grain", "everyday"],
    ingredients: "રવો, દહીં, ઈનો, આદુ, મરચાં, તેલ",
    note: "Instant semolina dhokla — soft and pillowy",
  },
  {
    id: "surti_locho",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Surti Locho", gu: "સુરતી લોચો" },
    mealTime: ["morning", "snack"],
    excludeDays: [],
    tags: ["steamed", "light", "satvic", "chana", "everyday"],
    ingredients: "ચણાની દાળ, પૌંઆ, અડદની દાળ, આદુ, મરચાં",
    note: "Surat's famous soft besan delight",
  },
  {
    id: "patra",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Patra", gu: "પાત્રા" },
    mealTime: ["morning", "snack"],
    excludeDays: [],
    tags: ["steamed", "light", "satvic", "leafy", "chana", "everyday"],
    ingredients: "અળવીના પાન, ચણાનો લોટ, ગોળ, આમલી, મસાલા",
    note: "Colocasia leaves rolled with spiced besan",
  },
  {
    id: "sukhdi",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Sukhdi", gu: "સુખડી" },
    mealTime: ["morning", "snack"],
    excludeDays: [],
    tags: ["warming", "heavy", "jaggery", "ghee", "grain", "festive"],
    ingredients: "ઘઉંનો લોટ, ગોળ, ઘી",
    note: "Wheat flour, jaggery, ghee — pure nourishing energy",
  },
  {
    id: "daliya",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Daliya", gu: "દળિયા" },
    mealTime: ["morning", "dinner"],
    excludeDays: [],
    tags: ["warming", "light", "satvic", "grain", "everyday"],
    ingredients: "ફાડા ઘઉં, શાકભાજી, મગની દાળ, ઘી, મસાલા",
    note: "Broken wheat porridge — warming as breakfast or dinner",
  },
  {
    id: "gathiya",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Gathiya", gu: "ગાઠિયા" },
    mealTime: ["morning", "snack"],
    excludeDays: [],
    tags: ["fried", "light", "rajasic", "chana", "everyday"],
    ingredients: "ચણાનો લોટ, અજમો, મરી, તેલ, મીઠું",
    note: "With green chutney and masala chai",
  },
  {
    id: "sev_mamra",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Sev Mamra", gu: "સેવ મમરા" },
    mealTime: ["morning", "snack"],
    excludeDays: [],
    tags: ["light", "chana", "grain", "everyday"],
    ingredients: "મમરા, સેવ, સીંગદાણા, હળદર, તેલ",
    note: "Light and crunchy — ideal any time of day",
  },
  {
    id: "chivda",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Chivda", gu: "ચેવડો" },
    mealTime: ["morning", "snack"],
    excludeDays: [],
    tags: ["fried", "light", "grain", "everyday"],
    ingredients: "પૌંઆ, મગફળી, દાળિયા, લીમડો, હળદર, તેલ",
    note: "Crispy spiced poha — classic Gujarati farsan",
  },
  {
    id: "bhel",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Bhel", gu: "ભેળ" },
    mealTime: ["snack"],
    excludeDays: [],
    tags: ["light", "grain", "everyday"],
    ingredients: "મમરા, સેવ, પાપડી, ડુંગળી, ટામેટાં, ચટણી",
    note: "Tangy puffed rice — a favourite street food",
  },
  {
    id: "makhana",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Makhana", gu: "મખાણા" },
    mealTime: ["morning", "snack"],
    excludeDays: [],
    tags: ["roasted", "light", "satvic", "fasting", "everyday"],
    ingredients: "મખાણા, ઘી, મીઠું, મરી",
    note: "Roasted lotus seeds — light and deeply satvic",
  },
  {
    id: "dabeli",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Dabeli", gu: "દાબેળી" },
    mealTime: ["morning", "snack"],
    excludeDays: [],
    tags: ["heavy", "rajasic", "root", "coconut", "everyday"],
    ingredients: "પાંઉ, બટાટા, દાબેલી મસાલો, દાડમ, સીંગ, ચટણી",
    note: "Spiced potato in a pav — Kutchi street food",
  },
  {
    id: "dal_dhokli",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Dal Dhokli", gu: "દાળ ઢોકળી" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    tags: ["light", "satvic", "toor", "grain", "everyday"],
    ingredients: "તુવેરની દાળ, ઘઉંનો લોટ, ગોળ, કોકમ, સીંગદાણા",
    note: "Wheat strips simmered in toor dal — comfort in a bowl",
  },
  {
    id: "gujarati_dal",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Gujarati Dal", gu: "ગુજરાતી દાળ" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    tags: ["light", "satvic", "toor", "everyday"],
    ingredients: "તુવેરની દાળ, ગોળ, આમલી, ટામેટાં, સીંગદાણા, મસાલા",
    note: "Sweet-tangy toor dal — the soul of a Gujarati thali",
  },
  {
    id: "undhiyu",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Undhiyu", gu: "ઉંધિયુ" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    months: [10, 11, 12, 1],
    tags: ["heavy", "satvic", "ghee", "root", "festive"],
    ingredients: "પાપડી, રતાળુ, બટાટા, કેળાં, રીંગણ, મુઠિયા, તેલ",
    note: "The king of Gujarati dishes — best at Uttarayan",
  },
  {
    id: "ringan_olo",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Ringan no Olo", gu: "રીંગણ નો ઓળો" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    tags: ["roasted", "light", "satvic", "everyday"],
    ingredients: "રીંગણ, ડુંગળી, ટામેટાં, લસણ, આદુ, તેલ",
    note: "Smoky roasted brinjal — rustic and flavourful",
  },
  {
    id: "sev_tameta",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Sev Tameta nu Shaak", gu: "સેવ ટામેટા" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    tags: ["light", "satvic", "everyday"],
    ingredients: "ટામેટાં, જાડી સેવ, ડુંગળી, લસણ, મસાલા, તેલ",
    note: "Tangy tomato curry crowned with crispy sev",
  },
  {
    id: "valor_papdi",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Valor Papdi nu Shaak", gu: "વાળોળ પાપડી" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    months: [10, 11, 12, 1, 2],
    tags: ["light", "satvic", "everyday"],
    ingredients: "વાલોળ પાપડી, અજમો, લસણ, તેલ, મસાલા",
    note: "Flat beans stir-fry — only in winter when fresh valor is available",
  },
  {
    id: "kadhi_khichdi",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Kadhi Khichdi", gu: "કઢી ખીચડી" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    tags: ["light", "satvic", "curd", "moong", "grain", "everyday"],
    ingredients: "ચોખા, મગની દાળ, દહીં, ચણાનો લોટ, ઘી, મસાલા",
    note: "The ultimate Gujarati pairing — curd kadhi with rice khichdi",
  },
  {
    id: "dudhi_chana_dal",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Dudhi Chana Dal", gu: "દૂધી ચણા દાળ" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [6],
    tags: ["light", "satvic", "cooling", "chana", "everyday"],
    ingredients: "દૂધી, ચણાની દાળ, ટામેટાં, મસાલા, તેલ",
    note: "Bottle gourd with chana dal — cooling and nourishing",
  },
  {
    id: "moong_dal_khichdi",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Moong Dal Khichdi", gu: "મૂગ ની ખીચડી" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    tags: ["light", "satvic", "moong", "grain", "fasting", "everyday"],
    ingredients: "ચોખા, મગની દાળ, હળદર, મીઠું, ઘી",
    note: "Pure and satvic — a staple of every Gujarati home",
  },
  {
    id: "batata_shaak",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Batata nu Shaak", gu: "બટાટા નું શાક" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    tags: ["light", "satvic", "root", "everyday"],
    ingredients: "બટાટા, રાઈ, જીરું, હળદર, લાલ મરચું, તેલ",
    note: "Everyday spiced potato curry with rotli",
  },
  {
    id: "tindola_shaak",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Tindola nu Shaak", gu: "તીંડોળા નું શાક" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    tags: ["light", "satvic", "cooling", "everyday"],
    ingredients: "ટીંડોળા, રાઈ, હળદર, ધાણાજીરું, તેલ",
    note: "Ivy gourd stir-fry — light and digestible",
  },
  {
    id: "shrikhand_puri",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Shrikhand Puri", gu: "શ્રીખંડ પૂરી" },
    mealTime: ["lunch"],
    excludeDays: [],
    tags: ["fried", "heavy", "satvic", "curd", "dairy", "grain", "festive"],
    ingredients: "મસ્કો દહીં, ખાંડ, એલચી, ઘઉંનો લોટ, તેલ",
    note: "Thick sweetened yoghurt with hot puris — festive joy",
  },
  {
    id: "vagharela_chawal",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Vagharela Chawal", gu: "વઘારેલા ચોખા" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    tags: ["light", "satvic", "grain", "everyday"],
    ingredients: "રાંધેલા ચોખા, રાઈ, જીરું, લીમડો, ડુંગળી, તેલ",
    note: "Tempered rice — quick and satisfying",
  },
  {
    id: "khichdi",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Khichdi", gu: "ખીચડી" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    tags: ["light", "satvic", "moong", "grain", "fasting", "everyday"],
    ingredients: "ચોખા, મગની ફોતરાવાળી દાળ, હળદર, મીઠું, પાણી",
    note: "Simplest and most healing — light on the gut at night",
  },
  {
    id: "vaghareli_khichdi",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Vaghareli Khichdi", gu: "વઘારેળી ખીચડી" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    tags: ["light", "satvic", "moong", "grain", "everyday"],
    ingredients: "ચોખા, મગની દાળ, શાકભાજી, ડુંગળી, ટામેટાં, ઘી",
    note: "Khichdi with a mustard-cumin temper",
  },
  {
    id: "bajra_rotla",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Bajra Rotla", gu: "બાજરા રોટલા" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    months: [9, 10, 11, 12, 1, 2, 3],
    tags: ["warming", "heavy", "grain", "ghee", "everyday"],
    ingredients: "બાજરાનો લોટ, મીઠું, પાણી, ઘી",
    note: "Thick millet flatbread with ghee — warming grain for cool months",
  },
  {
    id: "dudhi_shaak",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Dudhi nu Shaak", gu: "દૂધી નું શાક" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    tags: ["light", "satvic", "cooling", "everyday"],
    ingredients: "દૂધી, ટામેટાં, ધાણાજીરું, હળદર, તેલ",
    note: "Bottle gourd curry — cooling and gentle on digestion",
  },
  {
    id: "moong_dal",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Moong Dal", gu: "મૂગ ની દાળ" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    tags: ["light", "satvic", "moong", "everyday"],
    ingredients: "મગની દાળ, ઘી, રાઈ, જીરું, હળદર, લીંબુ",
    note: "Thin satvic moong dal — the most easily digested meal",
  },
  {
    id: "khakhra",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Khakhra", gu: "ખાખરા" },
    mealTime: ["morning", "snack"],
    excludeDays: [],
    tags: ["baked", "roasted", "light", "grain", "everyday"],
    ingredients: "ઘઉંનો લોટ, તેલ, મસાલા",
    note: "Crispy thin roasted flatbread — the everyday Gujarati snack",
  },
  {
    id: "khandvi",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Khandvi", gu: "ખાંડવી" },
    mealTime: ["morning", "snack"],
    excludeDays: [],
    tags: ["light", "satvic", "curd", "chana", "everyday"],
    ingredients: "ચણાનો લોટ, છાસ, આદુ, મરચાં, રાઈ, કોપરાનું છીણ",
    note: "Silky besan rolls in buttermilk — a Gujarati art form",
  },
  {
    id: "sheero",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Sheero", gu: "શીરો" },
    mealTime: ["morning", "snack"],
    excludeDays: [],
    tags: ["warming", "heavy", "ghee", "grain", "festive", "everyday"],
    ingredients: "રવો, ખાંડ, ઘી, દૂધ, એલચી, ડ્રાયફ્રૂટ્સ",
    note: "Semolina halwa with ghee and cardamom — deeply comforting",
  },
  {
    id: "lapsi",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Lapsi", gu: "લાપસી" },
    mealTime: ["morning", "dinner"],
    excludeDays: [],
    tags: ["warming", "light", "jaggery", "ghee", "grain", "everyday"],
    ingredients: "ફાડા ઘઉં, ગોળ, ઘી, એલચી",
    note: "Sweet broken wheat with jaggery — nourishing and warming",
  },
  {
    id: "puran_poli",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Puran Poli", gu: "પૂરણ પોળી" },
    mealTime: ["morning", "lunch"],
    excludeDays: [],
    tags: ["heavy", "satvic", "chana", "jaggery", "ghee", "grain", "festive"],
    ingredients: "ચણાની દાળ, ગોળ, એલચી, જાયફળ, ઘઉંનો લોટ, ઘી",
    note: "Sweet chana dal stuffed flatbread — festive and beloved",
  },
  {
    id: "sabudana_khichdi",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Sabudana Khichdi", gu: "સાબુદાણા ખીચડી" },
    mealTime: ["morning", "snack"],
    excludeDays: [],
    tags: ["light", "satvic", "sabudana", "fasting", "everyday"],
    ingredients: "સાબુદાણા, બટાટા, સીંગદાણાનો ભૂકો, લીલા મરચાં, ઘી",
    note: "Tapioca pearls with peanuts — light and satisfying",
  },
  {
    id: "sabudana_vada",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Sabudana Vada", gu: "સાબુદાણા વડા" },
    mealTime: ["morning", "snack"],
    excludeDays: [],
    tags: ["fried", "light", "sabudana", "fasting", "everyday"],
    ingredients: "સાબુદાણા, બાફેલા બટાટા, સીંગદાણા, મરચાં, તેલ",
    note: "Crispy tapioca patties — popular on fasting days",
  },
  {
    id: "batata_vada",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Batata Vada", gu: "બટાટા વડા" },
    mealTime: ["morning", "snack"],
    excludeDays: [],
    tags: ["fried", "heavy", "rajasic", "chana", "root", "everyday"],
    ingredients: "બટાટા, ચણાનો લોટ, આદુ, લસણ, મરચાં, કોથમરી, તેલ",
    note: "Spiced potato balls in besan batter — street food classic",
  },
  {
    id: "moong_chilla",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Moong Dal Chilla", gu: "મૂગ ની ચીલ્લા" },
    mealTime: ["morning", "snack"],
    excludeDays: [],
    tags: ["light", "satvic", "moong", "everyday"],
    ingredients: "મગની દાળ, આદુ, મરચાં, કોથમરી, મીઠું, તેલ",
    note: "Thin green moong pancake — protein-rich and light",
  },
  {
    id: "besan_chilla",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Besan Chilla", gu: "બેસણ ચીલ્લા" },
    mealTime: ["morning", "snack"],
    excludeDays: [],
    tags: ["light", "satvic", "chana", "everyday"],
    ingredients: "ચણાનો લોટ, ડુંગળી, ટામેટાં, મરચાં, અજમો, તેલ",
    note: "Chickpea flour pancake — quick and filling",
  },
  {
    id: "corn_poha",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Corn Poha", gu: "કોર્ન પૌંઆ" },
    mealTime: ["morning", "snack"],
    excludeDays: [],
    tags: ["light", "grain", "everyday"],
    ingredients: "મકાઈ, પૌંઆ, ડુંગળી, લીંબુ, મસાલા, તેલ",
    note: "Sweet corn with flattened rice — a colourful morning bowl",
  },
  {
    id: "methi_paratha",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Methi Paratha", gu: "મેથી પરાઠા" },
    mealTime: ["morning", "lunch"],
    excludeDays: [],
    months: [10, 11, 12, 1, 2, 3],
    tags: ["baked", "warming", "grain", "leafy", "everyday"],
    ingredients: "ઘઉંનો લોટ, મેથીની ભાજી, મસાલા, દહીં, તેલ",
    note: "Fenugreek-laced whole wheat paratha — only when fresh methi is available",
  },
  {
    id: "aloo_paratha",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Aloo Paratha", gu: "આલૂ પરાઠા" },
    mealTime: ["morning", "lunch"],
    excludeDays: [],
    tags: ["baked", "heavy", "grain", "root", "everyday"],
    ingredients: "ઘઉંનો લોટ, બાફેલા બટાટા, ડુંગળી, મસાલા, માખણ",
    note: "Stuffed potato paratha — hearty and satisfying",
  },
  {
    id: "paneer_paratha",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Paneer Paratha", gu: "પનીર પરાઠા" },
    mealTime: ["morning", "lunch"],
    excludeDays: [],
    tags: ["baked", "heavy", "grain", "dairy", "everyday"],
    ingredients: "ઘઉંનો લોટ, પનીર, મસાલા, કોથમરી, ઘી",
    note: "Cottage cheese stuffed paratha — rich and filling",
  },
  {
    id: "idli_sambhar",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Idli Sambhar", gu: "ઇડ્લી સાંભાર" },
    mealTime: ["morning", "snack"],
    excludeDays: [],
    tags: [
      "steamed",
      "fermented",
      "light",
      "satvic",
      "urad",
      "toor",
      "everyday",
    ],
    ingredients: "ચોખા, અડદની દાળ, તુવેરની દાળ, શાકભાજી, સાંભાર મસાલો",
    note: "Steamed rice cakes with lentil stew — light and wholesome",
  },
  {
    id: "rava_idli",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Rava Idli", gu: "રવા ઇડ્લી" },
    mealTime: ["morning", "snack"],
    excludeDays: [],
    tags: ["steamed", "light", "satvic", "grain", "everyday"],
    ingredients: "રવો, દહીં, ગાજર, કાજુ, ઈનો, રાઈ",
    note: "Semolina idli — no fermentation needed, ready in minutes",
  },
  {
    id: "uttapam",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Uttapam", gu: "ઉત્તપ્પા" },
    mealTime: ["morning", "snack"],
    excludeDays: [],
    tags: ["fermented", "light", "satvic", "urad", "grain", "everyday"],
    ingredients: "ચોખા, અડદની દાળ, ડુંગળી, ટામેટાં, મરચાં, કોથમરી",
    note: "Thick rice pancake with vegetables on top",
  },
  {
    id: "masala_dosa",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Masala Dosa", gu: "મસાળા ડોસા" },
    mealTime: ["morning", "snack"],
    excludeDays: [],
    tags: ["fermented", "light", "satvic", "urad", "grain", "root", "everyday"],
    ingredients: "ચોખા, અડદની દાળ, બટાટા, ડુંગળી, મસાલા, તેલ",
    note: "Crispy rice crepe with spiced potato filling",
  },
  {
    id: "chakli",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Chakli", gu: "ચકળી" },
    mealTime: ["snack"],
    excludeDays: [],
    tags: ["fried", "heavy", "grain", "festive"],
    ingredients: "ચોખાનો લોટ, ચણાનો લોટ, તલ, અજમો, માખણ, તેલ",
    note: "Spiral rice flour crisps — the Diwali favourite",
  },
  {
    id: "masala_toast",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Masala Toast", gu: "મસાળા ટોસ્ટ" },
    mealTime: ["morning", "snack"],
    excludeDays: [],
    tags: ["baked", "light", "grain", "everyday"],
    ingredients: "બ્રેડ, બટાટા, ડુંગળી, લીલી ચટણી, માખણ, સેવ",
    note: "Spiced chutney toast — the everyday quick breakfast",
  },
  {
    id: "bread_upma",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Bread Upma", gu: "બ્રેડ ઉપ્મા" },
    mealTime: ["morning", "snack"],
    excludeDays: [],
    tags: ["light", "grain", "everyday"],
    ingredients: "બ્રેડના ટુકડા, ડુંગળી, ટામેટાં, રાઈ, લીમડો, તેલ",
    note: "Tempered bread with vegetables — quick and tasty",
  },
  {
    id: "ponk_vada",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Ponk Vada", gu: "પોંક વડા" },
    mealTime: ["morning", "snack"],
    excludeDays: [],
    months: [11, 12, 1, 2],
    tags: ["fried", "heavy", "rajasic", "warming", "grain", "everyday"],
    ingredients: "પોંક (જુવાર), ચણાનો લોટ, આદુ, લસણ, મરચાં, તેલ",
    note: "Tender jowar kernel fritters — only during ponk season in Surat",
  },
  {
    id: "adadiya_pak",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Adadiya Pak", gu: "અડદિયા પાક" },
    mealTime: ["morning", "snack"],
    excludeDays: [],
    months: [11, 12, 1, 2],
    tags: ["warming", "heavy", "urad", "ghee", "jaggery", "festive"],
    ingredients: "અડદનો લોટ, ઘી, ખાંડ, ગુંદર, સૂંઠ, બદામ-પિસ્તા",
    note: "Urad flour and ghee winter tonic — warms from the inside",
  },
  {
    id: "mohanthal",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Mohanthal", gu: "મોહનથાળ" },
    mealTime: ["morning", "snack"],
    excludeDays: [],
    tags: ["warming", "heavy", "ghee", "chana", "dairy", "festive"],
    ingredients: "ચણાનો લોટ, ઘી, ખાંડ, દૂધ, એલચી, બદામ",
    note: "Roasted besan fudge with cardamom and saffron",
  },
  {
    id: "dudhi_halwa",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Dudhi Halwa", gu: "દૂધી હળવો" },
    mealTime: ["morning", "snack"],
    excludeDays: [],
    tags: ["heavy", "dairy", "ghee", "everyday"],
    ingredients: "દૂધી, દૂધ, માવો, ખાંડ, ઘી, એલચી",
    note: "Slow-cooked bottle gourd pudding with milk and sugar",
  },
  {
    id: "gajar_halwa",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Gajar Halwa", gu: "ગાજર હળવો" },
    mealTime: ["morning", "snack"],
    excludeDays: [],
    months: [11, 12, 1, 2, 3],
    tags: ["warming", "heavy", "dairy", "ghee", "everyday"],
    ingredients: "ગાજર, દૂધ, માવો, ખાંડ, ઘી, ડ્રાયફ્રૂટ્સ",
    note: "Carrot pudding slow-cooked in milk — winter carrots at their sweetest",
  },
  {
    id: "sev_usal",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Sev Usal", gu: "સેવ ઉસળ" },
    mealTime: ["snack", "lunch"],
    excludeDays: [],
    tags: ["heavy", "satvic", "chola", "everyday"],
    ingredients: "સફેદ વટાણા, ડુંગળી, લસણ, ટામેટાં, સેવ, પાંઉ, મસાલા",
    note: "Sprouted peas curry topped generously with sev",
  },
  {
    id: "ragda_patties",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Ragda Patties", gu: "રગડા પેટીસ" },
    mealTime: ["snack"],
    excludeDays: [],
    tags: ["fried", "heavy", "chola", "root", "everyday"],
    ingredients: "સફેદ વટાણા, બટાટા, ડુંગળી, ચટણી, મસાલા, તેલ",
    note: "White peas gravy with crispy potato patties",
  },
  {
    id: "pav_bhaji",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Pav Bhaji", gu: "પાઉ ભાજી" },
    mealTime: ["snack", "lunch"],
    excludeDays: [],
    tags: ["heavy", "rajasic", "onion", "root", "everyday"],
    ingredients: "બટાટા, વટાણા, ફ્લાવર, કેપ્સિકમ, ટામેટાં, પાંઉ, માખણ",
    note: "Spiced mashed vegetable medley with buttered pav",
  },
  {
    id: "vada_pav",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Vada Pav", gu: "વડા પાઉ" },
    mealTime: ["morning", "snack"],
    excludeDays: [],
    tags: ["fried", "heavy", "rajasic", "chana", "onion", "root", "everyday"],
    ingredients: "બટાટા, ચણાનો લોટ, લસણની ચટણી, પાંઉ, લીલા મરચાં, તેલ",
    note: "Batata vada in a pav — the great Indian fast food",
  },
  {
    id: "kanda_bhajia",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Kanda Bhajia", gu: "કાંદા ભજિયા" },
    mealTime: ["morning", "snack"],
    excludeDays: [],
    tags: ["fried", "heavy", "rajasic", "chana", "onion", "everyday"],
    ingredients: "ડુંગળી, ચણાનો લોટ, ધાણા, મરચાં, મીઠું, તેલ",
    note: "Crispy onion fritters — best eaten hot with chai",
  },
  {
    id: "batata_bhajia",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Batata Bhajia", gu: "બટાટા ભજિયા" },
    mealTime: ["morning", "snack"],
    excludeDays: [],
    tags: ["fried", "heavy", "rajasic", "chana", "root", "everyday"],
    ingredients: "બટાટાના ગોળ ટુકડા, ચણાનો લોટ, હળદર, મીઠું, તેલ",
    note: "Thin potato slices in spiced besan batter",
  },
  {
    id: "mirchi_bhajia",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Mirchi Bhajia", gu: "મિર્ચી ભજિયા" },
    mealTime: ["snack"],
    excludeDays: [],
    tags: ["fried", "heavy", "rajasic", "chana", "everyday"],
    ingredients: "મોટા લીલા મરચાં, ચણાનો લોટ, મીઠું, તેલ, અજમો",
    note: "Green chilli fritters — for the brave",
  },
  {
    id: "dahi_puri",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Dahi Puri", gu: "દહી પૂરી" },
    mealTime: ["snack"],
    excludeDays: [],
    tags: ["light", "curd", "everyday"],
    ingredients: "પૂરી, દહીં, બટાટા, ચણા, લીલી અને મીઠી ચટણી, સેવ",
    note: "Crispy puris with yogurt, chutneys, and sev",
  },
  {
    id: "papdi_chaat",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Papdi Chaat", gu: "પાપડી ચાટ" },
    mealTime: ["snack"],
    excludeDays: [],
    tags: ["light", "curd", "everyday"],
    ingredients: "પાપડી, બટાટા, દહીં, ચટણી, ડુંગળી, સેવ",
    note: "Crispy wafers with curd, tamarind, and sev",
  },
  {
    id: "kachori",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Kachori", gu: "કચોરી" },
    mealTime: ["morning", "snack"],
    excludeDays: [],
    tags: ["fried", "heavy", "rajasic", "moong", "everyday"],
    ingredients: "મેંદો, મગની દાળ, મસાલા, તેલ",
    note: "Flaky pastry stuffed with spiced moong or onion filling",
  },
  {
    id: "lilva_kachori",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Lilva Kachori", gu: "લીલવા કચોરી" },
    mealTime: ["morning", "snack"],
    excludeDays: [],
    months: [10, 11, 12, 1],
    tags: ["fried", "heavy", "everyday"],
    ingredients: "મેંદો, તુવેરના લીલવા, આદુ, મરચાં, લીંબુ, તેલ",
    note: "Fresh pigeon pea stuffed kachori — a winter Gujarati treat",
  },
  {
    id: "sev_khamani",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Sev Khamani", gu: "સેવ ખમણ" },
    mealTime: ["morning", "snack"],
    excludeDays: [],
    tags: ["light", "satvic", "chana", "everyday"],
    ingredients: "ખમણ, સેવ, દાડમ, લસણ, રાઈ, તેલ",
    note: "Crumbled dhokla tossed with tempering and sev",
  },
  {
    id: "pani_puri",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Pani Puri", gu: "પાણી પૂરી" },
    mealTime: ["snack"],
    excludeDays: [],
    tags: ["light", "everyday"],
    ingredients: "પૂરી, ફુદીનાનું પાણી, મીઠી ચટણી, બાફેલા બટાટા, ચણા",
    note: "Crispy hollow puris with tangy tamarind water",
  },
  {
    id: "sev_puri",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Sev Puri", gu: "સેવ પૂરી" },
    mealTime: ["snack"],
    excludeDays: [],
    tags: ["light", "everyday"],
    ingredients: "પૂરી, બટાટા, ડુંગળી, ચટણી, ટામેટાં, ઝીણી સેવ",
    note: "Flat puris loaded with chutneys, potato, and sev",
  },
  {
    id: "masala_puri",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Masala Puri", gu: "મસાળા પૂરી" },
    mealTime: ["snack"],
    excludeDays: [],
    tags: ["heavy", "chola", "everyday"],
    ingredients: "પૂરી, વટાણાની ગ્રેવી, ડુંગળી, ટામેટાં, ચટણી, સેવ",
    note: "Puris in a spiced green pea gravy",
  },
  {
    id: "corn_bhel",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Corn Bhel", gu: "કોર્ન ભેળ" },
    mealTime: ["snack"],
    excludeDays: [],
    tags: ["light", "everyday"],
    ingredients: "મકાઈ, ડુંગળી, ટામેટાં, ચટણી, લીંબુ, સેવ",
    note: "Sweet corn with chutneys and crunchy namkeen",
  },
  {
    id: "ghughra",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Ghughra", gu: "ઘૂઘરા" },
    mealTime: ["morning", "snack"],
    excludeDays: [],
    tags: ["fried", "heavy", "jaggery", "coconut", "festive"],
    ingredients: "મેંદો, માવો, સૂકું કોપરું, ખાંડ, ડ્રાયફ્રૂટ્સ, તેલ",
    note: "Deep-fried sweet dumplings stuffed with dry fruits and coconut",
  },
  {
    id: "guvar_shaak",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Guvar nu Shaak", gu: "ગ્વાર નું શાક" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    tags: ["light", "satvic", "everyday"],
    ingredients: "ગુવાર, અજમો, લસણ, ટામેટાં, મસાલા, તેલ",
    note: "Cluster beans stir-fry — slightly bitter, very nutritious",
  },
  {
    id: "fansi_shaak",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Fansi nu Shaak", gu: "ફણસી નું શાક" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    tags: ["light", "satvic", "coconut", "everyday"],
    ingredients: "ફણસી, લસણ, રાઈ, હળદર, કોપરાનું છીણ, તેલ",
    note: "French beans sautéed with mustard and coconut",
  },
  {
    id: "karela_shaak",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Karela nu Shaak", gu: "કારેલા નું શાક" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    tags: ["light", "satvic", "cooling", "everyday"],
    ingredients: "કારેલા, ગોળ, ધાણાજીરું, હળદર, લાલ મરચું, તેલ",
    note: "Bitter gourd — an acquired taste that heals",
  },
  {
    id: "kela_shaak",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Kela nu Shaak", gu: "કેળા નું શાક" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    tags: ["heavy", "satvic", "root", "everyday"],
    ingredients: "કાચા કેળા, રાઈ, હળદર, મરચું, તેલ",
    note: "Raw banana curry — a filling and grounding shaak",
  },
  {
    id: "turiya_shaak",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Turiya nu Shaak", gu: "તૂરિયા નું શાક" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    tags: ["light", "satvic", "cooling", "everyday"],
    ingredients: "તૂરિયા, જીરું, લસણ, ટામેટાં, મસાલા, તેલ",
    note: "Ridge gourd curry — light and easily digestible",
  },
  {
    id: "mag_shaak",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Mag nu Shaak", gu: "મગ નું શાક" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    tags: ["heavy", "satvic", "moong", "warming", "everyday"],
    ingredients: "આખા મગ, ડુંગળી, લસણ, ટામેટાં, મસાલા, તેલ",
    note: "Whole moong bean curry — protein-rich and warming",
  },
  {
    id: "vatana_shaak",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Vatana nu Shaak", gu: "વટાણા નું શાક" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    tags: ["light", "satvic", "everyday"],
    ingredients: "લીલા વટાણા, ટામેટાં, ડુંગળી, લસણ, આદુ, ગરમ મસાલો",
    note: "Green pea curry — sweet, fresh, and wholesome",
  },
  {
    id: "methi_shaak",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Methi nu Shaak", gu: "મેથી નું શાક" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    months: [10, 11, 12, 1, 2, 3],
    tags: ["light", "satvic", "warming", "leafy", "everyday"],
    ingredients: "મેથીની ભાજી, લસણ, લાલ સૂકું મરચું, હળદર, તેલ",
    note: "Fenugreek leaf stir-fry — best when fresh methi is in season",
  },
  {
    id: "suva_shaak",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Suva Bhaji nu Shaak", gu: "સુવા ભાજી" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    tags: ["light", "satvic", "leafy", "everyday"],
    ingredients: "સુવાની ભાજી, લસણ, મરચાં, હળદર, તેલ",
    note: "Dill leaves stir-fry — fragrant and underrated",
  },
  {
    id: "palak_shaak",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Palak nu Shaak", gu: "પાલક નું શાક" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    tags: ["light", "satvic", "leafy", "everyday"],
    ingredients: "પાલક, લસણ, આદુ, લીલા મરચાં, તેલ",
    note: "Spiced spinach — simple and iron-rich",
  },
  {
    id: "lili_tuver",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Lili Tuver nu Shaak", gu: "લીલી તુવેર" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    months: [11, 12, 1],
    tags: ["light", "satvic", "toor", "everyday"],
    ingredients: "લીલી તુવેરના દાણા, ટામેટાં, આદુ, લસણ, મસાલા, તેલ",
    note: "Fresh pigeon peas — only available for a few winter weeks",
  },
  {
    id: "kothi_shaak",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Kothi nu Shaak", gu: "કોઠી નું શાક" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    tags: ["heavy", "satvic", "coconut", "everyday"],
    ingredients: "કોઠી (વાલોળના દાણા), તલ, કોપરાનું છીણ, લસણ, મસાલા",
    note: "Hyacinth beans with sesame and coconut",
  },
  {
    id: "papri_shaak",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Papri nu Shaak", gu: "પાપડી નું શાક" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    tags: ["light", "satvic", "everyday"],
    ingredients: "પાપડી, અજમો, લસણ, ટામેટાં, મસાલા, તેલ",
    note: "Fresh flat beans tempered with cumin and chilli",
  },
  {
    id: "aloo_gobi",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Aloo Gobi", gu: "આલૂ ગોભી" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    tags: ["light", "satvic", "root", "everyday"],
    ingredients: "બટાટા, ફ્લાવર, ડુંગળી, ટામેટાં, ગરમ મસાલો, તેલ",
    note: "Potato and cauliflower — the classic dry sabzi",
  },
  {
    id: "panchkutiyu",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Panchkutiyu Shaak", gu: "પંચ કૂટીઉ" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    tags: ["satvic", "festive", "everyday"],
    ingredients: "પાપડી, બટાટા, શક્કરિયા, રીંગણ, વાલોળ, મસાલા, તેલ",
    note: "Five-vegetable Gujarati dry curry — festive and flavourful",
  },
  {
    id: "methi_matar",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Methi Matar", gu: "મેથી મટર" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    months: [10, 11, 12, 1, 2, 3],
    tags: ["light", "satvic", "leafy", "everyday"],
    ingredients: "મેથીની ભાજી, વટાણા, મલાઈ, ડુંગળી, લસણ, તેલ",
    note: "Fenugreek and green peas — both fresh in winter",
  },
  {
    id: "palak_paneer",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Palak Paneer", gu: "પાલક પનીર" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    tags: ["satvic", "leafy", "dairy", "everyday"],
    ingredients: "પાલક, પનીર, ડુંગળી, લસણ, ગરમ મસાલો, માખણ",
    note: "Cottage cheese in creamy spinach gravy",
  },
  {
    id: "matar_paneer",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Matar Paneer", gu: "મટર પનીર" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    tags: ["satvic", "dairy", "onion", "everyday"],
    ingredients: "લીલા વટાણા, પનીર, ટામેટાં, ડુંગળી, કાજુ, તેલ",
    note: "Peas and paneer in a tomato-onion gravy",
  },
  {
    id: "paneer_bhurji",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Paneer Bhurji", gu: "પનીર ભૂર્જી" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    tags: ["rajasic", "dairy", "onion", "everyday"],
    ingredients: "પનીર, ડુંગળી, ટામેટાં, કેપ્સિકમ, મસાલા, તેલ",
    note: "Scrambled cottage cheese with spices — quick and hearty",
  },
  {
    id: "ringan_batata",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Ringan Batata nu Shaak", gu: "રીંગણ બટાટા" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    tags: ["satvic", "root", "everyday"],
    ingredients: "રીંગણ, બટાટા, રાઈ, જીરું, ટામેટાં, મસાલા, તેલ",
    note: "Brinjal and potato together — a rustic everyday shaak",
  },
  {
    id: "bhindi_masala",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Bhindi Masala", gu: "ભીંડી મસાળા" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    tags: ["roasted", "satvic", "everyday"],
    ingredients: "ભીંડા, ડુંગળી, આમચૂર પાવડર, ધાણાજીરું, તેલ",
    note: "Okra stir-fried with spices — crispy and flavourful",
  },
  {
    id: "tameta_batata",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Tameta Batata nu Shaak", gu: "ટામેટા બટાટા" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    tags: ["satvic", "root", "everyday"],
    ingredients: "ટામેટાં, બટાટા, રાઈ, જીરું, ધાણાજીરું, મીઠું, તેલ",
    note: "Tomato and potato curry — tangy and comforting",
  },
  {
    id: "marcha_batata",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Marcha Batata nu Shaak", gu: "મરચા બટાટા" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    tags: ["satvic", "root", "everyday"],
    ingredients: "કેપ્સિકમ મરચાં, બટાટા, હળદર, રાઈ, તેલ",
    note: "Capsicum and potato stir-fry — vibrant and tasty",
  },
  {
    id: "suva_moong_dal",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Suva Moong Dal", gu: "સુવા મૂગ ની દાળ" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    tags: ["light", "satvic", "moong", "leafy", "everyday"],
    ingredients: "મગની દાળ, સુવાની ભાજી, લસણ, ટામેટાં, તેલ",
    note: "Moong dal cooked with fresh dill — aromatic and light",
  },
  {
    id: "trevti_dal",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Trevti Dal", gu: "ત્રેવટી દાળ" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    tags: ["heavy", "satvic", "moong", "toor", "masoor", "everyday"],
    ingredients: "મગની દાળ, તુવેરની દાળ, મસૂરની દાળ, આદુ, લસણ, ઘી",
    note: "Three-lentil blend — hearty and nutritious",
  },
  {
    id: "chola_shaak",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Chola nu Shaak", gu: "ચોળા નું શાક" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    tags: ["heavy", "satvic", "chola", "everyday"],
    ingredients: "ચોળા, ડુંગળી, ટામેટાં, આદુ, લસણ, ગરમ મસાલો",
    note: "Black-eyed peas curry — wholesome and earthy",
  },
  {
    id: "gujarati_kadhi",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Gujarati Kadhi", gu: "ગુજરાતી કઢી" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    tags: ["light", "satvic", "curd", "everyday"],
    ingredients: "દહીં, ચણાનો લોટ, ગોળ, આદુ, મરચાં, લીમડો, ઘી",
    note: "Sweet-tangy yogurt kadhi — best with plain rice",
  },
  {
    id: "tameta_kadhi",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Tameta Kadhi", gu: "ટામેટા કઢી" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    tags: ["light", "satvic", "curd", "everyday"],
    ingredients: "દહીં, ચણાનો લોટ, ટામેટાં, રાઈ, જીરું, ઘી",
    note: "Tomato-based kadhi — a lighter, tangier variation",
  },
  {
    id: "vaal_dal",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Vaal Dal", gu: "વાળ ની દાળ" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    tags: ["heavy", "satvic", "vaal", "everyday"],
    ingredients: "વાલના દાણા, ગોળ, રાઈ, જીરું, લસણ, તેલ",
    note: "Field beans dal — a bold, earthy Gujarati staple",
  },
  {
    id: "masoor_dal",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Masoor Dal", gu: "મસૂર ની દાળ" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    tags: ["light", "satvic", "masoor", "everyday"],
    ingredients: "મસૂરની દાળ, ડુંગળી, ટામેટાં, લસણ, તેલ",
    note: "Red lentil dal — quick to cook, easy to love",
  },
  {
    id: "chana_dal_tadka",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Chana Dal Tadka", gu: "ચણા ની દાળ" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [6],
    tags: ["heavy", "satvic", "chana", "ghee", "everyday"],
    ingredients: "ચણાની દાળ, ડુંગળી, ટામેટાં, લસણ, સૂકા મરચાં, ઘી",
    note: "Split chickpea dal with a generous ghee temper",
  },
  {
    id: "mogar",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Mogar", gu: "મોગર" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    tags: ["light", "satvic", "moong", "everyday"],
    ingredients: "ફણગાવેલા મગ, રાઈ, હળદર, લીંબુ, મીઠું, તેલ",
    note: "Whole sprouted moong curry — light and very satvic",
  },
  {
    id: "masala_bhaat",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Masala Bhaat", gu: "મસાળા ભાત" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    tags: ["satvic", "grain", "festive", "everyday"],
    ingredients: "ચોખા, શાકભાજી, આખા મસાલા, હળદર, તેલ",
    note: "Spiced rice with whole garam masala — fragrant and festive",
  },
  {
    id: "lemon_rice",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Lemon Rice", gu: "લીંબુ ચોખા" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    tags: ["light", "satvic", "grain", "everyday"],
    ingredients: "ચોખા, લીંબુ, મગફળી, રાઈ, લીમડો, હળદર, તેલ",
    note: "Tangy turmeric rice with mustard and curry leaves",
  },
  {
    id: "dahi_chawal",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Dahi Chawal", gu: "દહી ભાત" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    tags: ["light", "satvic", "cooling", "curd", "grain", "everyday"],
    ingredients: "ચોખા, દહીં, રાઈ, લીમડો, અડદની દાળ, આદુ",
    note: "Curd rice — cooling, simple, and deeply satisfying",
  },
  {
    id: "jeera_rice",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Jeera Rice", gu: "જીરા ભાત" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    tags: ["light", "satvic", "grain", "everyday"],
    ingredients: "બાફેલા ચોખા, જીરું, ઘી, મીઠું",
    note: "Cumin-tempered rice — the perfect neutral base",
  },
  {
    id: "veg_pulao",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Veg Pulao", gu: "સબ્ઝી પૂળાઉ" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    tags: ["satvic", "grain", "everyday"],
    ingredients: "ચોખા, વટાણા, ગાજર, ફ્લાવર, ગરમ મસાલો, ઘી",
    note: "Vegetable pulao — lightly spiced, aromatic",
  },
  {
    id: "coconut_rice",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Coconut Rice", gu: "નારિયેળ ભાત" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    tags: ["light", "satvic", "grain", "coconut", "everyday"],
    ingredients: "ચોખા, તાજું છીણેલું કોપરું, રાઈ, લીમડો, સૂકા લાલ મરચાં, તેલ",
    note: "South-style coconut rice with curry leaves and mustard",
  },
  {
    id: "veg_biryani",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Veg Biryani", gu: "સબ્ઝી બિરયાની" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    tags: ["heavy", "rajasic", "grain", "onion", "festive"],
    ingredients: "ચોખા, મિશ્ર શાકભાજી, બિરયાની મસાલો, કેસર, દહીં, ડુંગળી, ઘી",
    note: "Layered spiced rice with vegetables — a celebratory dish",
  },
  {
    id: "bhakri",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Bhakri", gu: "ભાકરી" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    tags: ["heavy", "grain", "everyday"],
    ingredients: "જાડો ઘઉંનો લોટ, મીઠું, પાણી, ઘી",
    note: "Thick jowar flatbread — rustic staple of Gujarat",
  },
  {
    id: "makkai_rotlo",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Makkai no Rotlo", gu: "મકાઈ નો રોટલો" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    tags: ["warming", "heavy", "grain", "everyday"],
    ingredients: "મકાઈનો લોટ, મીઠું, પાણી, માખણ",
    note: "Thick corn flatbread with a pat of white butter",
  },
  {
    id: "puri_shaak",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Puri Shaak", gu: "પૂરી શાક" },
    mealTime: ["morning", "lunch"],
    excludeDays: [],
    tags: ["fried", "heavy", "grain", "root", "everyday"],
    ingredients: "ઘઉંનો લોટ, બટાટા, ટામેટાં, મસાલા, તેલ",
    note: "Deep-fried puffed bread with potato sabzi",
  },
  {
    id: "bhatura_chole",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Bhatura Chole", gu: "ભટૂરા છોળ" },
    mealTime: ["morning", "lunch"],
    excludeDays: [6],
    tags: ["fried", "heavy", "rajasic", "chana", "grain", "onion", "everyday"],
    ingredients: "મેંદો, દહીં, કાબુલી ચણા, ડુંગળી, ટામેટાં, છોલે મસાલો, તેલ",
    note: "Fluffy fried bread with spiced chickpeas — indulgent",
  },
  {
    id: "phulka",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Phulka", gu: "ફૂળ્કા" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    tags: ["light", "satvic", "grain", "everyday"],
    ingredients: "ઝીણો ઘઉંનો લોટ, પાણી, ઘી",
    note: "Thin whole wheat rotli puffed on flame — lightest flatbread",
  },
  {
    id: "dudhi_muthiya",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Dudhi Muthiya", gu: "દૂધી મૂઠિયા" },
    mealTime: ["morning", "snack"],
    excludeDays: [],
    tags: ["steamed", "light", "satvic", "everyday"],
    ingredients: "દૂધી, ઘઉંનો કકરો લોટ, ચણાનો લોટ, મેથીની ભાજી, મસાલા, તેલ",
    note: "Steamed bottle gourd dumplings — wholesome and light",
  },
  {
    id: "basundi",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Basundi", gu: "બાસૂંદી" },
    mealTime: ["morning", "snack", "lunch"],
    excludeDays: [],
    tags: ["heavy", "dairy", "festive"],
    ingredients: "દૂધ, ખાંડ, એલચી, ચારોળી, કેસર, બદામ-પિસ્તા",
    note: "Reduced sweetened milk with saffron and cardamom",
  },
  {
    id: "amrakhand",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Amrakhand", gu: "આમ્રખંડ" },
    mealTime: ["morning", "lunch"],
    excludeDays: [],
    months: [4, 5, 6],
    tags: ["heavy", "cooling", "curd", "mango", "festive"],
    ingredients: "મસ્કો દહીં, કેરીનો રસ, ખાંડ, એલચી",
    note: "Mango shrikhand — only when Alphonso mangoes are in season",
  },
  {
    id: "churma_ladoo",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Churma Ladoo", gu: "ચૂરમા લાડૂ" },
    mealTime: ["morning", "snack"],
    excludeDays: [],
    tags: ["warming", "heavy", "ghee", "grain", "jaggery", "festive"],
    ingredients: "ઘઉંનો કકરો લોટ, ગોળ, ઘી, ખસખસ, એલચી",
    note: "Ghee-rich whole wheat balls — energy-dense and festive",
  },
  {
    id: "shakarpara",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Shakarpara", gu: "શક્કરપારા" },
    mealTime: ["snack"],
    excludeDays: [],
    tags: ["fried", "heavy", "grain", "jaggery", "festive"],
    ingredients: "મેંદો અથવા ઘઉંનો લોટ, ખાંડ, ઘી, તેલ",
    note: "Sweet diamond-shaped fried biscuits — Diwali favourite",
  },
  {
    id: "jalebi",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Jalebi", gu: "જલેબી" },
    mealTime: ["morning", "snack"],
    excludeDays: [],
    tags: ["fried", "heavy", "festive", "everyday"],
    ingredients: "મેંદો, ખાંડની ચાસણી, કેસર, તેલ",
    note: "Crispy spiral sweets soaked in sugar syrup",
  },
  {
    id: "doodh_pak",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Doodh Pak", gu: "દૂધ પાક" },
    mealTime: ["morning", "lunch"],
    excludeDays: [],
    tags: ["heavy", "dairy", "grain", "festive"],
    ingredients: "દૂધ, બાસમતી ચોખા, ખાંડ, એલચી, ચારોળી, કેસર",
    note: "Saffron rice pudding slow-cooked in milk — festive dessert",
  },
  {
    id: "kadhi_pakoda",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Kadhi Pakoda", gu: "કઢી પકોડા" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    tags: ["fried", "heavy", "curd", "chana", "everyday"],
    ingredients: "દહીં, ચણાનો લોટ, ડુંગળીના ભજિયા, આદુ, મરચાં, ઘી",
    note: "Besan fritters dunked in yogurt kadhi — hearty and warming",
  },
  {
    id: "mix_veg",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Mix Vegetable Shaak", gu: "મિક્સ સબ્ઝી" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    tags: ["satvic", "everyday"],
    ingredients: "બટાટા, વટાણા, ગાજર, ફ્લાવર, કેપ્સિકમ, ટામેટાં, મસાલા, તેલ",
    note: "Seasonal vegetables together — a wholesome everyday shaak",
  },
  {
    id: "chole",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Chole", gu: "છોળ" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [6],
    tags: ["heavy", "rajasic", "chana", "onion", "everyday"],
    ingredients: "કાબુલી ચણા, ડુંગળી, ટામેટાં, છોલે મસાલો, આદુ, લસણ, તેલ",
    note: "Spiced chickpea curry — bold and satisfying",
  },
  {
    id: "rajma_chawal",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Rajma Chawal", gu: "રાજ્મા ચાવળ" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    tags: ["heavy", "rajasic", "rajma", "grain", "onion", "everyday"],
    ingredients: "રાજમા, ડુંગળી, ટામેટાં, લસણ, આદુ, ગરમ મસાલો, ચોખા",
    note: "Kidney bean curry over steamed rice — North Indian comfort",
  },
  {
    id: "dhana_dal",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Dhana Dal", gu: "ધાણા ની દાળ" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    tags: ["light", "satvic", "everyday"],
    ingredients: "ધાણાની દાળ, રાઈ, હળદર, હિંગ, તેલ",
    note: "Coriander-tempered lentils — fragrant and light",
  },
  {
    id: "stuffed_capsicum",
    cuisine: "gujarati",
    diet: "veg",
    names: { en: "Stuffed Capsicum", gu: "ભરેલ મરચા" },
    mealTime: ["lunch", "dinner"],
    excludeDays: [],
    tags: ["satvic", "dairy", "everyday"],
    ingredients: "કેપ્સિકમ, બાફેલા બટાટા, પનીર, ડુંગળી, ગરમ મસાલો, તેલ",
    note: "Capsicum filled with spiced paneer or potato stuffing",
  },
];
